LOCATION_EN = {
    'Amman': 'Amman',
    'Amsterdam': 'Amsterdam',
    'Banja Luka, Bosnia or Belgrade, Serbia': 'Banja Luka or Belgrade',
    'Boise, Idaho, USA; Denver, Colorado, USA; Jackson, Wyoming, USA; Portland, Oregon, USA; Salt Lake City, Utah, USA; Vancouver, Washington, USA': 'Northwest USA & Canada',
    'Boston': 'Boston',
    'Chicago IL': 'Chicago',
    'Europe & Asia': 'Europe & Asia',
    'Gdańsk': 'Gdansk',
    'India': 'India',
    'Los Angeles': 'Los Angeles',
    'Los Angeles or Remote': 'Los Angeles or Remote',
    'Louisville': 'Louisville',
    'Minnesota': 'Minnesota',
    'New York': 'New York',
    'New York City': 'New York City',
    'Noida': 'Noida',
    'Remote': 'Remote',
    'Remote - Global (Anywhere)': 'Remote (Global)',
    'Remote - US': 'Remote (USA)',
    'Remote - USA': 'Remote (USA)',
    'Remote, Ontario': 'Remote (Ontario)',
    'Remote, USA': 'Remote (USA)',
    'Rome': 'Rome',
    'Russia': 'Russia',
    'SF Bay Area': 'San Francisco Bay Area',
    'San Francisco': 'San Francisco',
    'Slovakia': 'Slovakia',
    'Springfield, IL': 'Springfield',
    'Texas': 'Texas',
    'Toronto': 'Toronto',
    'Unknown': 'Unknown',
    'Vancouver, WA': 'Vancouver',
    'Архангельск,': 'Arkhangelsk',
    'Балашиха,': 'Balashikha',
    'Батайск,': 'Bataysk',
    'Дедовск,': 'Dedovsk',
    'Казань,': 'Kazan',
    'Красногорск,': 'Krasnogorsk',
    'Краснодар,': 'Krasnodar',
    'Люберцы,': 'Lyubertsy',
    'Москва,': 'Moscow',
    'Мытищи,': 'Mytishchi',
    'Пермь,': 'Perm',
    'Пушкино,': 'Pushkino',
    'Санкт-Петербург,': 'Saint Petersburg',
    'Солнечногорск,': 'Solnechnogorsk',
    'Сочи,': 'Sochi',
    'Фрязино,': 'Fryazino',
    'Челябинск,': 'Chelyabinsk',
    'Алтайский край': 'Altai Krai',
    'Амурская область': 'Amur Oblast',
    'Архангельская область': 'Arkhangelsk Oblast',
    'Астраханская область': 'Astrakhan Oblast',
    'Белгородская область': 'Belgorod Oblast',
    'Брянская область': 'Bryansk Oblast',
    'Владимирская область': 'Vladimir Oblast',
    'Волгоградская область': 'Volgograd Oblast',
    'Вологодская область': 'Vologda Oblast',
    'Воронежская область': 'Voronezh Oblast',
    'Город Байконур': 'Baikonur',
    'Город Москва': 'Moscow',
    'Город Санкт-Петербург': 'Saint Petersburg',
    'Город Севастополь': 'Sevastopol',
    'Донецкая Народная Республика': 'Donetsk Republic',
    'Еврейская автономная область': 'Jewish Autonomous Oblast',
    'Забайкальский край': 'Zabaykalsky Krai',
    'Запорожская область': 'Zaporozhye Oblast',
    'Ивановская область': 'Ivanovo Oblast',
    'Иркутская область': 'Irkutsk Oblast',
    'Кабардино-Балкарская Республика': 'Kabardino-Balkaria',
    'Калининградская область': 'Kaliningrad Oblast',
    'Калужская область': 'Kaluga Oblast',
    'Камчатский край': 'Kamchatka Krai',
    'Карачаево-Черкесская Республика': 'Karachay-Cherkessia',
    'Кемеровская область - Кузбасс': 'Kemerovo Oblast',
    'Кировская область': 'Kirov Oblast',
    'Костромская область': 'Kostroma Oblast',
    'Краснодарский край': 'Krasnodar Krai',
    'Красноярский край': 'Krasnoyarsk Krai',
    'Курганская область': 'Kurgan Oblast',
    'Курская область': 'Kursk Oblast',
    'Ленинградская область': 'Leningrad Oblast',
    'Липецкая область': 'Lipetsk Oblast',
    'Луганская Народная Республика': 'Lugansk Republic',
    'Магаданская область': 'Magadan Oblast',
    'Московская область': 'Moscow Oblast',
    'Мурманская область': 'Murmansk Oblast',
    'Ненецкий автономный округ': 'Nenets Autonomous Okrug',
    'Нижегородская область': 'Nizhny Novgorod Oblast',
    'Новгородская область': 'Novgorod Oblast',
    'Новосибирская область': 'Novosibirsk Oblast',
    'Омская область': 'Omsk Oblast',
    'Оренбургская область': 'Orenburg Oblast',
    'Орловская область': 'Oryol Oblast',
    'Пензенская область': 'Penza Oblast',
    'Пермский край': 'Perm Krai',
    'Приморский край': 'Primorsky Krai',
    'Псковская область': 'Pskov Oblast',
    'Республика Адыгея (Адыгея)': 'Republic of Adygea',
    'Республика Алтай': 'Altai Republic',
    'Республика Башкортостан': 'Republic of Bashkortostan',
    'Республика Бурятия': 'Republic of Buryatia',
    'Республика Дагестан': 'Republic of Dagestan',
    'Республика Ингушетия': 'Republic of Ingushetia',
    'Республика Калмыкия': 'Republic of Kalmykia',
    'Республика Карелия': 'Republic of Karelia',
    'Республика Коми': 'Republic of Komi',
    'Республика Крым': 'Republic of Crimea',
    'Республика Марий Эл': 'Republic of Mari El',
    'Республика Мордовия': 'Republic of Mordovia',
    'Республика Саха (Якутия)': 'Sakha Republic',
    'Республика Северная Осетия - Алания': 'North Ossetia-Alania',
    'Республика Татарстан (Татарстан)': 'Republic of Tatarstan',
    'Республика Тыва': 'Tuva Republic',
    'Республика Хакасия': 'Republic of Khakassia',
    'Ростовская область': 'Rostov Oblast',
    'Рязанская область': 'Ryazan Oblast',
    'Самарская область': 'Samara Oblast',
    'Саратовская область': 'Saratov Oblast',
    'Сахалинская область': 'Sakhalin Oblast',
    'Свердловская область': 'Sverdlovsk Oblast',
    'Сириус федеральная территория': 'Sirius Federal Territory',
    'Смоленская область': 'Smolensk Oblast',
    'Ставропольский край': 'Stavropol Krai',
    'Тамбовская область': 'Tambov Oblast',
    'Тверская область': 'Tver Oblast',
    'Томская область': 'Tomsk Oblast',
    'Тульская область': 'Tula Oblast',
    'Тюменская область': 'Tyumen Oblast',
    'Удмуртская Республика': 'Udmurt Republic',
    'Ульяновская область': 'Ulyanovsk Oblast',
    'Хабаровский край': 'Khabarovsk Krai',
    'Ханты-Мансийский автономный округ - Югра': 'Khanty-Mansi Autonomous Okrug',
    'Херсонская область': 'Kherson Oblast',
    'Челябинская область': 'Chelyabinsk Oblast',
    'Чеченская Республика': 'Chechen Republic',
    'Чувашская Республика - Чувашия': 'Chuvash Republic',
    'Чукотский автономный округ': 'Chukotka Autonomous Okrug',
    'Ямало-Ненецкий автономный округ': 'Yamalo-Nenets Autonomous Okrug',
    'Ярославская область': 'Yaroslavl Oblast',
}